name: Scraping Job

on:
  schedule:
    # Every 15 minutes between 6am-8pm UTC Mon-Thu
    - cron: "0-59/15 6-21 * * 1-4"
  workflow_dispatch: # optional manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Supabase job
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
        run: python scrape.py
